name: nodeauth-worker
owner: nodeauth
package: .
kind: wasmer.io/App.v0

jobs:
  - name: nodeauth-daily-backup
    trigger: '0 2 * * *'
    action:
      fetch:
        path: /api/cron/wasmer/backup
        timeout: 30s
